

#ifndef __CONSTANTS__
#define __CONSTANTS__

int NUMBER_OF_DIFFERENT_MEDICINES;
int NUMBER_OF_PRODUCTION_LINES;
int THRESHOLD_OF_NEEDED_LIQUID_MEDICINES;
int THRESHOLD_OF_NEEDED_PILL_MEDICINES;
int THRESHOLD_OF_DEFECTIVE_LIQUIDS;
int THRESHOLD_OF_DEFECTIVE_PILLS;
int SIMULATION_TIME;
int MIN_LIQUID_LEVEl;
int MAX_LIQUID_LEVEL;
int NUMBER_OF_PILLS_IN_PLASTIC_CONTAINER;
int MIN_THROUGHPUT_OF_PRODUCTION_LINE;
int MAX_THROUGHPUT_OF_PRODUCTION_LINE;
int MIN_NUMBER_OF_INSPECTING_WORKERS;
int MIN_NUMBER_OF_PACKAGING_WORKERS;
int MAX_NUMBER_OF_INSPECTING_WORKERS;
int MAX_NUMBER_OF_PACKAGING_WORKERS;
int NUMBER_OF_PACKAGING_WORKERS;
int NUMBER_OF_INSPECTING_WORKERS;


#endif


